### Variable para la URL local
@baseUrl = http://localhost:3000

### ===== LOCAL =====

### Obtener todos los géneros (públicos)
GET {{baseUrl}}/api/genders
Content-Type: application/json

### Crear Género Hombres
POST {{baseUrl}}/api/genders
Content-Type: application/json
Cookie: auth=<TOKEN_ADMIN>

{
  "name": "Hombres"
}

### Crear Género Mujeres
POST {{baseUrl}}/api/genders
Content-Type: application/json
Cookie: auth=<TOKEN_ADMIN>

{
  "name": "Mujeres"
}

### Crear Género Unisex
POST {{baseUrl}}/api/genders
Content-Type: application/json
Cookie: auth=<TOKEN_ADMIN>

{
  "name": "Unisex"
}


### ===== PRODUCCIÓN (Railway) =====
@prodUrl = https://proyecto-venta-productos-production.up.railway.app

### Obtener todos los géneros en producción
GET {{prodUrl}}/api/genders
Content-Type: application/json

### Crear Género Hombres en producción
POST {{prodUrl}}/api/genders
Content-Type: application/json
Cookie: auth=<TOKEN_ADMIN>

{
  "name": "Hombres"
}

### Crear Género Mujeres en producción
POST {{prodUrl}}/api/genders
Content-Type: application/json
Cookie: auth=<TOKEN_ADMIN>

{
  "name": "Mujeres"
}

### Crear Género Unisex en producción
POST {{prodUrl}}/api/genders
Content-Type: application/json
Cookie: auth=<TOKEN_ADMIN>

{
  "name": "Unisex"
}