### obtener todas las marcas
GET http://localhost:3000/api/brands



### POST
POST http://localhost:3000/api/brands
Content-Type: application/json

{
  "name": "nike",
  "description": "nike style(No ropa deportiva)",
  "website": "https://www.nike.com/en/",
  "countryOfOrigin": "EEUU"
}

### buscar una marca
GET http://localhost:3000/api/brands/2




### PUT 
PUT  http://localhost:3000/api/brands/3
Content-Type: application/json

{
  "name": "adidas",
  "description": "apple argentina",
  "website": "https://www.adidas.com/en/",
  "countryOfOrigin": "Brasil",
  "logo": "https://www.example.com/images/product123.jpg"
}


### modificar una marca  
PATCH http://localhost:3000/api/brands/3
Content-Type: application/json

{
  "description": "leonelabuin2002@gmail.com",
  "website":"https://www.hawainy.com/en/"
}



###DELETE

DELETE http://localhost:3000/api/brands/4
