### obtener todos los characters
GET http://localhost:3000/api/clients

### POST
### POST
# @name createClient
POST http://localhost:3000/api/clients
Content-Type: application/json

{
  "dni": 44290906,
  "name": "Leonel",
  "surname": "Abuin",
  "mail": "leonelabuin2002@gmail.com",
  "phoneNumber": "3364290054",
  "userName": "Leo29",
  "password": "Delpotro20"
}



### buscar un cliente 
###ID
@id = {{createClient.response.body.data.id}}
### obtener un producto
GET http://localhost:3000/api/clients/{{id}}




### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/clients/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
"name": "Javier",
  "surname": "Milei",
  "dni": 45656400,
  "mail": "JGM2024@gmail.com",
  "phoneNumbre": 3415699866
}


### POST
# @name createClientToDeleted
POST http://localhost:3000/api/clients
Content-Type: application/json

{
  "dni": 44290906,
  "name": "Leonel",
  "surname": "Abuin",
  "mail": "leonelabuin@gmail.com",
  "phoneNumber": 154290054
}


###ID
@idToDeleted = {{createClientToDeleted.response.body.data.id}}


DELETE http://localhost:3000/api/clients/{{idToDeleted}}
