### obtener todos las categorias
GET http://localhost:3000/api/categories


### obtener una categoria 
GET http://localhost:3000/api/categories/1

### crear un nuevo character
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "camisetas de futbol",
  "description": "camisetas de futbol de todas las marcas y equipos"
}


### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/categories/2
Content-Type: application/json

{
"name": "Pantalones",
"description": "Explora nuestra amplia selección de pantalones que combinan estilo y comodidad para cualquier ocasión."
}


### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/categories/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{

"surname": "Remeras",
"description": "Remeras de algodon y poliester para entrenamiento y juego.",
}

### borrar una categoria 
DELETE http://localhost:3000/api/categories/1


### 4. Pantalones y Shorts
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Pantalones y Shorts",
  "description": "Shorts de juego y pantalones de entrenamiento térmicos."
}

### 5. Ropa de Entrenamiento
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Ropa de Entrenamiento",
  "description": "Remeras técnicas, musculosas y calzas de compresión."
}

### 6. Camperas y Buzos
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Camperas y Buzos",
  "description": "Indumentaria de abrigo deportiva y rompevientos."
}

### 7. Accesorios Deportivos
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Remeras",
  "description": "Remeras de algodon y poliester para entrenamiento y juego."
}

### 8. Pelotas
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Pelotas",
  "description": "Balones reglamentarios de fútbol, básquet y voley."
}

### 9. Equipamiento de Tenis
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Equipamiento de Tenis",
  "description": "Raquetas, pelotas de tenis y ropa específica para court."
}

### 10. Mochilas y Bolsos
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Mochilas y Bolsos",
  "description": "Bolsos de entrenamiento y mochilas porta botines."
}








### Variable para la URL del Backend
@baseUrl = https://proyecto-venta-productos-production.up.railway.app

### 4. Pantalones y Shorts
POST {{baseUrl}}/api/categories
Content-Type: application/json

{
  "name": "Pantalones y Shorts",
  "description": "Shorts de juego y pantalones de entrenamiento térmicos."
}

### 5. Ropa de Entrenamiento
POST {{baseUrl}}/api/categories
Content-Type: application/json

{
  "name": "Ropa de Entrenamiento",
  "description": "Remeras técnicas, musculosas y calzas de compresión."
}

### 6. Camperas y Buzos
POST {{baseUrl}}/api/categories
Content-Type: application/json

{
  "name": "Camperas y Buzos",
  "description": "Indumentaria de abrigo deportiva y rompevientos."
}

### 7. Remeras
POST {{baseUrl}}/api/categories
Content-Type: application/json

{
  "name": "Remeras",
  "description": "Remeras de algodon y poliester para entrenamiento y juego."
}

### 8. Pelotas
POST {{baseUrl}}/api/categories
Content-Type: application/json

{
  "name": "Pelotas",
  "description": "Balones reglamentarios de fútbol, básquet y voley."
}

### 9. Equipamiento de Tenis
POST {{baseUrl}}/api/categories
Content-Type: application/json

{
  "name": "Equipamiento de Tenis",
  "description": "Raquetas, pelotas de tenis y ropa específica para court."
}

### 10. Mochilas y Bolsos
POST {{baseUrl}}/api/categories
Content-Type: application/json

{
  "name": "Mochilas y Bolsos",
  "description": "Bolsos de entrenamiento y mochilas porta botines."
}