### obtener todos los distribuidores
GET http://localhost:3000/api/distributors


### obtener un distribuidor
GET http://localhost:3000/api/distributors/2045845042

### crear un nuevo distibuidor
POST http://localhost:3000/api/distributors
Content-Type: application/json

{
  "CUIL": 2045845042,
  "name":"Leonel",
  "surname":"Abuin",
  "email": "leoy@gmail.com",
  "phoneNumber":"3364290054",
  "address":"Los pinos 2650"
}


### modificar un distribuidor(patch)
PATCH http://localhost:3000/api/distributors/2045845042
Content-Type: application/json

{
  "email": "leonelabuin2002@gmail.com",
  "phoneNumber":"3364290054",
  "address":"Los pinos 2650"
}


### modificar un distribuidor(put)
PUT http://localhost:3000/api/distributors/2045845042
Content-Type: application/json

{
  "CUIL": 2045845555,
  "name":"Juan Sebastian",
  "surname":"Veron",
  "email": "jbVeron@gmail.com",
  "phoneNumber":"3364290554",
  "address":"Los pinos 2650"
}

### borrar un character
DELETE http://localhost:3000/api/distributors/2045845555