### obtener todos los characters
GET http://localhost:3000/api/brands


### obtener un character
GET http://localhost:3000/api/brands/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un nuevo character
POST http://localhost:3000/api/brands
Content-Type: application/json

{
  "name": "Levi's",
  "description": "Levi's es la esencia misma del denim de calidad y moda perdurable. Con su emblemática gama de jeans y ropa, la marca personifica el estilo estadounidense contemporáneo. Desde su establecimiento en 1853, Levi's ha representado autenticidad, innovación y un estilo que perdura a través del tiempo.",
}


### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/brands/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
"name": "Nike",
"description": "Nike es la encarnación del rendimiento y el estilo deportivo. Desde su fundación en 1971, la marca ha liderado la industria con su calzado y ropa innovadores, siendo la elección de atletas y entusiastas del deporte en todo el mundo. Con su icónico logo Swoosh, Nike continúa siendo un símbolo de excelencia y motivación para alcanzar nuevas metas en el deporte y la vida cotidiana.",
}


### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/brands/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{

"name": "Nike",
"description": "Nike es la encarnación del rendimiento y el estilo deportivo. Desde su fundación en 1971, la marca ha liderado la industria con su calzado y ropa innovadores, siendo la elección de atletas y entusiastas del deporte en todo el mundo. Con su icónico logo Swoosh, Nike continúa siendo un símbolo de excelencia y motivación para alcanzar nuevas metas en el deporte y la vida cotidiana."
}

### borrar un character
DELETE http://localhost:3000/api/brands/a02b91bc-3769-4221-beb1-d7a3aeba7dad