### obtener todos los characters
GET http://localhost:3000/api/products


### obtener un character
GET http://localhost:3000/api/products/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### POST
# @name createProduct
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "zapatilla",
  "description": "azules",
  "waist": "12",
  "calification": 10,
  "stock": 10,
  "imagen": 10,
  "prices":[2]
}


### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/products/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "name": "joggig",
  "description": "rojo",
  "waist": 9,
  "calification": 10,
  "stock": 10,
  "imagen": 10 
}

### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/products/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{

  "calification": 10,
  "stock": 10,
  "imagen": 10  
}

### borrar un character
DELETE http://localhost:3000/api/products/a02b91bc-3769-4221-beb1-d7a3aeba7dad