### obtener todos los productos
GET http://localhost:3000/api/products

### POST
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "tablet",
  "description": "celular 4''",
  "waist": "S",
  "calification": 8,
  "stock": 100,
  "imagen": "https://www.example.com/images/product123.jpg",
  "brand":1,
  "category": 1,
  "distributor": 1
}


### buscar un producto 
###ID
### obtener un producto
GET http://localhost:3000/api/products/1


// SE PUEDE HACER UN UPDATE DE PRODUCTO? COMO HACER CON EL ARRAY DE PRECIOS?

### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/products/1
Content-Type: application/json

{
  "calification": 10,
  "stock": 50000
}





### DELETE a product

DELETE http://localhost:3000/api/products/4




###PUT
PUT  http://localhost:3000/api/products/1
Content-Type: application/json

{
  "name": "remera",
  "description": "color negra 5",
  "waist": "S",
  "calification": 8,
  "stock": 500,
  "imagen": "https://www.example.com/images/product123.jpg",
  "brand":2,
  "category": 1,
  "distributor": 1
}