### obtener todos los productos
GET http://localhost:3000/api/products

### POST
# @name createProduct
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "pantalones",
  "description": "rojos",
  "waist": "M",
  "calification": 5,
  "stock": 50,
  "imagen": 24
}



### buscar un producto 
###ID
@id = {{createProduct.response.body.data.id}}
### obtener un producto
GET http://localhost:3000/api/products/{{id}}


// SE PUEDE HACER UN UPDATE DE PRODUCTO? COMO HACER CON EL ARRAY DE PRECIOS?

### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/products/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{

  "calification": 10,
  "stock": 10,
  "imagen": 10  
}


### POST
# @name createProductToDelete
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "auriculares",
  "description": "verdes",
  "waist": "XL",
  "calification": 7,
  "stock": 100,
  "imagen": 2854
}






### DELETE a product
@idToDelete = {{createProductToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/products/{{idToDelete}}
